---
title: "Event Study: RStudio Addin"
author: "Dr. Simon Müller"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: readable
    highlight: tango
    css: kable.css
vignette: >
  %\VignetteIndexEntry{Event Study Addin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Motivation {#motivation}

We have developed a user-friendly and intuitive Event Study add-in for the widely-used RStudio IDE. Designed with a similar interface as our web frontend, this add-in offers users the advantage of seamlessly working with the results directly in R. Additionally, the add-in supports numerous test statistics, aiming to expedite your Event Study process and enhance efficiency.

# How to Use {#how-to-use}

Upon installing the EventStudy package, our RStudio Add-in is automatically installed as well (provided you are using RStudio as your IDE). You can easily launch the add-in by clicking on *Event Study* in the Add-ins menu. If you are unable to locate the add-in in the menu, you can find it by selecting *Browse Add-ins\...*, which opens a window containing the available add-ins.

Within the add-in, you can work in a manner similar to our self-explanatory web API interface. However, unlike the web API interface, it is essential to use an EventStudyTools key, which can be obtained from our [website](https://www.eventstudytools.com/).

Please note that we have designed the add-in to include an upload field for the three required data files (request, firm, and market data). Although we utilize only the file path internally, the upload field simplifies the process for users.

# How to Cite {#how-to-cite}

Please cite our work in your [publication](https://eventstudytools.com/how-cite-eventstudytoolscom).
